language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy

install: pip install --upgrade pip setuptools .[test]

script: py.test pygal/ --flake8 --cov-report= --cov=pygal

after_success: coveralls

sudo: false
