name: pygal
description: A python svg graph plotting library
license: LGPLv3
public: true
url: http://www.pygal.org/

menu:
  - Documentation:
      link: /documentation/
  - Support:
      link: /support/
  - Download:
      link: /download/
  
ribbon: 
  url: http://github.com/Kozea/pygal

project (git):
  url: git://github.com/Kozea/pygal.git
  path: pygal

vcs (git):
  url: git://github.com/Kozea/pygal.git
  path: /var/db/git/pygal.git

code browser (github):
  project name: Kozea/pygal

bug tracker (github):
  base url: http://github.com/Kozea/pygal/issues
  project name: Kozea/pygal

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: pygal
