name: pygal
description: A python svg graph plotting library
license: LGPLv3
public: true
url: http://www.pygal.org/
pystil: https://kozea.pystil.org/pystil.js

menu:
  - Try it online:
      link: http://cabaret.pygal.org/
  - News:
      link: /news/
  - Documentation:
      link: /documentation/
  - Support:
      link: /support/
  - Download:
      link: /download/

footer:
  - A Kozea Project:
      link: http://community.kozea.fr/
  - Optimized for Standards:
      link: http://validator.w3.org/check?uri=referer

project (git):
  url: git://github.com/Kozea/pygal.git
  path: pygal

code browser (github):
  project name: Kozea/pygal
  ribbon: Fork me on GitHub

bug tracker (github):
  project name: Kozea/pygal

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: pygal
